name: Breathe478
options:
  bundleIdPrefix: com.breathe478
  deploymentTarget:
    watchOS: "10.0"
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "8BDAZ8X68U"
    CODE_SIGN_STYLE: Automatic

targets:
  # Shared framework (optional, but helps with code organization)
  # For now we include Shared sources directly in each target

  # iOS App
  Breathe478 iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Shared
        excludes:
          - "**/.DS_Store"
      - path: Breathe478 iOS
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.breathe478.ios
        PRODUCT_NAME: "Breathe478"
        INFOPLIST_FILE: "Breathe478 iOS/Info.plist"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_IDENTITY: "Apple Development"
    dependencies:
      - target: Breathe478 Watch App
        embed: watch2
    entitlements:
      path: Breathe478 iOS/Breathe478iOS.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    scheme:
      testTargets: []
      gatherCoverageData: false

  # Watch App
  Breathe478 Watch App:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: Shared
        excludes:
          - "**/.DS_Store"
      - path: Breathe478 Watch App
        excludes:
          - "**/.DS_Store"
          - Models/BreathingPhase.swift
          - Models/BreathingState.swift
          - Models/SessionRecord.swift
          - Views/Theme.swift
          - Views/PetalView.swift
          - Managers/HealthKitManager.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.breathe478.ios.watchkitapp
        PRODUCT_NAME: "Breathe478 Watch App"
        INFOPLIST_FILE: "Breathe478 Watch App/Info.plist"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
    entitlements:
      path: Breathe478 Watch App/Breathe478.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    scheme:
      testTargets: []
      gatherCoverageData: false
