name: Breathe478
options:
  bundleIdPrefix: com.breathe478
  deploymentTarget:
    watchOS: "11.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  Breathe478 Watch App:
    type: application
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: Breathe478 Watch App
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.breathe478.watchapp
        PRODUCT_NAME: "Breathe478"
        INFOPLIST_FILE: "Breathe478 Watch App/Info.plist"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    entitlements:
      path: Breathe478 Watch App/Breathe478.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
